jobs:
- job: build
  steps:
  - checkout: git://{project_name}/ADLS@{branch}

  - task: CopyFiles@2
    inputs:
        contents: 'ADLS/Data/**'
        targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: ADLS_artifact
