trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
- group: IRISBuildVG

resources:
  repositories:
  - repository: MLOps
    type: git
    name: AzureDevOps/MLOps
    ref: master

stages:
- stage: Build
  displayName: "Build stage"
  jobs:
  - template: templates/build-template.yml

- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: templates/deploy-template.yml
