trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    pip install requests
  displayName: "Install python dependencies using pip"

- script: |
    python3 $(Build.SourcesDirectory)/tests/test.py 
  displayName: 'Testing MLOps - ACI'
  condition: always()